UPDATE `products` SET `description2` = 'Świecący Grzyb to niewielki, ale niezwykle charakterystyczny organizm występujący w jaskiniach, również w tych wewnątrz pokoi informatyków. Osiąga do 30 cm wysokości, z kapeluszem szerokim na około 8 cm. W młodym stadium jest ciemny i matowy, ale po pełnym dojrzeniu zaczyna emitować intensywne, chłodne niebieskie światło. Świecący Grzyb ujawnia to, co ukryte – pod jego światłem niewidzialne staje się widzialne, a iluzje tracą moc. Dlatego bywa wykorzystywany przez magów do wykrywania zaklęć iluzji, ukrytych przejść lub duchów.' WHERE `products`.`idProducts` = 1; 
UPDATE `products` SET `description2` = 'Odbijogódki to niewielkie jagody rosnące głównie na porzuconych placach budowy i skażonych e-paiperosami terenach miejskich. Ich owoce – intensywnie czerwone jagody o błyszczącej, elastycznej skorupie – wyglądają apetycznie, lecz zachowują się zupełnie nieprzewidywalnie. Pokryte kauczukowatą warstwą zabarwioną naturalną betaniną, potrafią odbijać się od twardych powierzchni jak piłeczki, nierzadko zagrażając oczom lub nosom nieostrożnych zbieraczy. Co gorsza, niektóre egzemplarze zawierają w środku drobiny… betonu – nikt nie wie, jak się tam znalazły, ale ich spożycie nie kończy się tragicznie dla zębów, co najwyżej dla twojego żołądka.' WHERE `products`.`idProducts` = 2; 
UPDATE `products` SET `description2` = 'Płomienny Tulipan to niezwykle rzadka i legendarna roślina, której płatki zdają się płonąć wiecznym, cichym ogniem. W przeciwieństwie do iluzji czy naturalnych bioluminescencyjnych zjawisk, jego płomień jest prawdziwy – emituje ciepło, nie niszcząc jednak samej rośliny. Z każdym powiewem wiatru płomienie tańczą na krawędziach płatków niczym żywe istoty, nie tracąc przy tym intensywności ani formy. Płomienny Tulipan pochodzi z głębokich trzewi świata – z Wulkanicznych Jaskiń Al’Zharra, ukrytych pod zgasłym, lecz wciąż aktywnym duchowo kraterem Góry Kresh-Tahar.' WHERE `products`.`idProducts` = 3; 
UPDATE `products` SET `description2` = 'Woskogrzyby to niezwykłe, półroślinne, półmineralne istoty grzybopodobne, które wyrastają pojedynczo lub w skupiskach przypominających różowe świece ułożone w kręgi. oskogrzyby występują naturalnie w Lesie Cukrowych Mgieł, położonym na obrzeżach magicznej krainy Słodkiej Otchłani – eterycznego rezerwatu między wymiarem snu a światem materialnym.' WHERE `products`.`idProducts` = 4; 
UPDATE `products` SET `description2` = 'Zielona istota o zbyt ostrym apetycie. Kiełek to pozornie niewinna, mała mięsożerna roślina, która w młodości przypomina zwykły pęd o jaskrawozielonych listkach i łodydze pokrytej meszkiem. Jednak już od wczesnych dni wykazuje wyraźny głód – z początku zadowala się owadami, potem małymi gryzoniami... aż w końcu zaczyna interesować się większymi formami życia. Co ważne – nie jest rośliną bezmyślną. Kiełek wykazuje instynkt łowiecki, a nawet zalążki inteligencji. Kiełek pochodzi z Topieli Zgniłego Poranka – mglistych, wiecznie wilgotnych bagien znajdujących się na granicy Królestwa Dziczy i Pustki Snów.' WHERE `products`.`idProducts` = 5; 
UPDATE `products` SET `description2` = 'Zarodniki Świecącego Grzyba to mikroskopijne, srebrzysto-niebieski kuleczki, które delikatnie pulsują światłem, ledwie widocznym gołym okiem. Choć z pozoru niewielkie i kruche, zawierają w sobie olbrzymi potencjał energetyczny – są żywym magazynem światła UV, które wykorzystują do kiełkowania i wzrostu. W warunkach naturalnych zarodniki unoszą się w powietrzu nocą, osiadając tylko tam, gdzie panuje harmonia między ciepłem, światłem i spokojem. Zarodniki należy przechowywać na słońcu, najlepiej w przezroczystej fiolce z kryształowego szkła. Szkło powinno być odkażone eliksirem ochronnym, by nie dopuścić do ich zanieczyszczenia. Codzienna ekspozycja na światło UV (min. 3 godziny dziennie) jest kluczowa – bez niej zarodniki zapadają w stan uśpienia i mogą zginąć.' WHERE `products`.`idProducts` = 6; 
UPDATE `products` SET `description2` = 'Nasiona Odbijogódek są niewielkimi, eliptycznymi obiektami wielkości orzecha laskowego, pokrytymi połyskującą, elastyczną kauczukową skorupą, intensywnie zabarwioną betaniną – naturalnym barwnikiem o kolorze głębokiej buraczkowej czerwieni. Z wyglądu przypominają jaskrawe kulki do gry... i zachowują się podobnie. Każde nasiono ma naturalną zdolność odbicia się od niemal każdej powierzchni z nienaturalną siłą, co czyni ich wysiew aktem zarówno rolnictwa, jak i sportu ekstremalnego.' WHERE `products`.`idProducts` = 7; 
UPDATE `products` SET `description2` = 'Nasiona tej ognistej rośliny mają postać twardych, czarnych bryłek przypominających miniaturowe kawałki obsydianu – ostre, lśniące, ciężkie jak na swój rozmiar. W ich wnętrzu tli się mikroskopijny płomyk, widoczny tylko przy całkowitym zaciemnieniu i w odpowiedniej temperaturze (powyżej 60°C). Przy dotknięciu rozgrzewają się lekko – to znak, że „czuwają”. Nasiona są aktywne energetycznie, ale w stanie uśpienia, dopóki nie poczują prawdziwego ognia w ziemi. Nasiona muszą być zasadzone wyłącznie w glebie spalonej, wulkanicznej lub przepalonej przez magiczny ogień. Zwykła ziemia sprawi, że nasiono się zapiecze i nie wykiełkuje. ' WHERE `products`.`idProducts` = 8; 
UPDATE `products` SET `description2` = 'Nasiona Woskogrzybów to niewielkie, różowe kulki lub pręciki zatopione w lekko pachnącym, naturalnym wosku. Struktura zewnętrzna przypomina topniejącą świecę, ale wewnątrz znajduje się aktywna grzybnia – żywa, delikatna sieć magicznych włókien. W przeciwieństwie do wielu magicznych grzybów, Woskogrzyby są skrajnie wrażliwe na temperaturę. Włożenie nasion do piekarnika, pozostawienie ich w pobliżu źródła ciepła powyżej 40°C lub wystawienie na silne promienie słoneczne trwale niszczy grzybnię.' WHERE `products`.`idProducts` = 9; 
UPDATE `products` SET `description2` = 'Nasiona Kiełka to ziarnka o brązowej barwie, przypominające z wyglądu żołędzie, lecz znacznie twardsze. Wewnątrz znajduje się zaczątek rośliny mięsożernej – niezwykle cierpliwej, ale niepokojąco inteligentnej. Jej wzrost uzależniony jest od bardzo specyficznych warunków… w tym harmonogramu pracy. Nasiono może z czasem wykształcić minikły przedwczesnego wzrostu – ostre mięsaczki, które „testują teren”. Nie krwawią, ale szczypią złośliwie. ' WHERE `products`.`idProducts` = 10; 
UPDATE `products` SET `description2` = 'Eliksir Wzrostu to błyszczący, jasnoróżowy płyn, delikatnie gęsty, o zapachu świeżo skoszonej trawy i nutą cytrynowego porostu. Jego mikroskopijne składniki magiczne działają bezpośrednio na strukturę tkanek roślinnych, stymulując błyskawiczne namnażanie komórek, asymilację magicznych minerałów i przyspieszoną fotosyntezę. Produkt wyjątkowo skuteczny – ale potężny. Nieodpowiednie użycie może prowadzić do mutacji, nieprzewidywalnych reakcji lub przejęcia inicjatywy przez samą roślinę...' WHERE `products`.`idProducts` = 11; 
UPDATE `products` SET `description2` = 'Eliksir Uspokajający to chłodny, zielony płyn, pachnący nieco jak deszcz po burzy i stary papier. Stworzony został przez dawnych alchemików do kontroli nastrojów szczególnie złośliwych okazów roślinnych, które przejawiają zbyt dużo emocji… lub zębów. Eliksir nie leczy, nie tresuje, tylko wycisza. Tworzy wokół rośliny aurę tłumienia reakcji agresywnych i skłonności do dramatyzmu botanicznego.' WHERE `products`.`idProducts` = 12; 
UPDATE `products` SET `description2` = 'Eliksir Ocieplenia to gęsty, bursztynowo-pomarańczowy płyn, który wydziela ciepło niemal natychmiast po otwarciu. Jego aromat przypomina skondensowane słońce z dodatkiem lekko pikantnego imbiru i słodkich, dojrzałych owoców. Stworzony został z esencji magicznych płomieni oraz ekstraktów termalnych roślin pustynnych i tropikalnych. Podnosi temperaturę w otoczeniu korzeni i łodyg rośliny, tworząc wokół niej magiczną „otulinę cieplną”. ' WHERE `products`.`idProducts` = 13; 
UPDATE `products` SET `description2` = 'Eliksir Ochronny to przezroczysty, lekko niebieski, gwieździsty płyn, który w dotyku przypomina jedwabisty rosę. Jego zapach to mieszanka leśnej żywicy, mięty i odrobiny przypraw korzennych, co sprawia, że działa również odstraszająco na magiczne owady i pasożyty. Po podlaniu tworzy na powierzchni rośliny niewidzialną, magiczną barierę ochronną, która trwa do 24 godzin na każde 100 ml użytego eliksiru. Bariera ta neutralizuje ataki szkodników, takich jak magiczne mszyce, złowrogie pająki czy pasożytnicze liany.' WHERE `products`.`idProducts` = 14; 
UPDATE `products` SET `description2` = 'Diamentowe Nożyce to mistrzowskie narzędzie ogrodnicze wykute z czystego, magicznego diamentu, połączonego z lekkim, ale niezwykle wytrzymałym stopem mithrilu. Ostrza błyszczą jak gwiazdy w najciemniejszą noc, a ich powierzchnia jest niemal niewrażliwa na zarysowania, korozję czy zużycie. Przecinają nawet najtwardsze i najbardziej odpornie rośliny, w tym te z rozlanym woskiem czy pokryte pyłem wulkanicznym.' WHERE `products`.`idProducts` = 15; 
UPDATE `products` SET `description2` = 'Rękawice Termiczne są wykonane z unikalnego, chłonnego materiału z lodowych pnącz oraz smoczych łusek, dzięki czemu potrafią całkowicie blokować przenikanie ciepła, niezależnie od jego źródła. Materiał jest lekki, elastyczny i przyjemny w dotyku, a jednocześnie odporny na ogień, lawę oraz magiczne płomienie.' WHERE `products`.`idProducts` = 16; 
UPDATE `products` SET `description2` = 'Dom, który rośnie razem z tobą. Magiczna Doniczka to misternie wykonany pojemnik z lekkiej gliny, przeplatanej delikatnymi włóknami gwieździstymi. Jej powierzchnia lekko pulsuje żywym światłem, dostosowując się do potrzeb rośliny, która w niej rośnie.' WHERE `products`.`idProducts` = 17; 
UPDATE `products` SET `description2` = 'Szmaragdowa Łopata jest wykuta z jednolitego, głęboko zielonego szmaragdu, który wzmocniono magicznymi żyłkami mithrilu. Łopata nie ulega uszkodzeniom mechanicznym — nie pęka, nie rdzewieje, nie tępi się. Podczas kopania łopata absorbuje energię fizyczną użytkownika i przekierowuje ją wprost do ostrza, co sprawia, że ziemia ustępuje niemal bez oporu. Dzięki magii łopata zmniejsza obciążenie mięśni rąk i pleców, pozwalając pracować dłużej i efektywniej.' WHERE `products`.`idProducts` = 18; 




UPDATE `products` SET `description` = 'Wiecznie palący się kwiat, sprowadzony prosto z otchłani wulkanicznych jaskiń.' WHERE `products`.`idProducts` = 3; 