name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -v -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} "echo Meow!"

    - name: Deploy code to GCP
      run: |
        rsync -avz --exclude '.git' ./ ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:/var/www/html/
